spring:
  application:
    name: mod-inn-reach
  jackson:
    default-property-inclusion: non_null
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:192.168.153.128}:${DB_PORT:5432}/${DB_DATABASE:folio}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    hibernate:
      format_sql: true

server.port: 8081
folio.tenant.validation.enabled: true
