server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
folio:
  tenant:
    validation:
      enabled: false
